### ISSUE TITLE
pip install -e maripower returns error

### ISSUE THREAD

**Issue by TinaZhangTing** [52North/WeatherRoutingTool#2]
Hi! when running the command"pip install -e maripower", there returns an error:  maripower is not a valid editable requirement. I guess something was missing or not right. Could you please help me?

**Comment by EHJ-52n** [comment]
Please provide more details.

**Comment by TinaZhangTing** [comment]
my env is win10, below is the error 
![Snipaste_2024-07-10_10-43-01](https://github.com/52North/WeatherRoutingTool/assets/43131477/f5e48b4b-15c1-4112-8a09-80c9c06eb483)

**Comment by EHJ-52n** [comment]
Please follow the installation instructions. Do you have maripower available?

**Comment by MartinPontius** [comment]
Hi @TinaZhangTing ,

the description of how to get/use mariPower and what's its purpose hasn't been clear in the README. Sorry for that.

The mariPower Python package as well as the WeatherRoutingTool has been developed within the research project [MariData](https://maridata.org/en/start_en).
The mariPower package allows to predict engine power under various environmental conditions for specific ships investigated in the project. You can find more details about the package and the project as a whole in the following publication: [https://proceedings.open.tudelft.nl/imdc24/article/view/875](https://proceedings.open.tudelft.nl/imdc24/article/view/875)

The mariPower package is closed source software and this will most likely not change in the future. However, as power demand varies from ship to ship users have to provide code for making power predictions on their own suitable to the use case. I.e. predictions from mariPower will probably not provide good power predictions in your use case anyway.
You can integrate your own ship with its own power demand by implementing a new [ship class](https://github.com/52North/WeatherRoutingTool/blob/main/WeatherRoutingTool/ship/ship.py) and using it in the config.

One way to quickly circumvent these restrictions is to use the configuration `ALGORITHM_TYPE='speedy_isobased'` and specifying the config parameter `'CONSTANT_FUEL_RATE'`. This will assume a constant fuel rate of the vessel in any condition (high waves, low waves, etc.) and at any time. Of course, results will be highly inaccurate, but it is a way to quickly try and test the code and get some first ideas of possible routes.

In the future, it would be interesting to integrate general empirical formulas for power demand which provide reasonable results based on a small set of general ship parameters provided by the user like length and draft of the ship. However, for optimal results it is necessary to have a power prediction framework specifically designed for your ship(s). This could be based, e.g., on physical laws or data driven.

Let me know, if you have further questions.

**Comment by MartinPontius** [comment]
The README has now been updated accordingly.
