### ISSUE TITLE
Request for Access and Cloning Instructions for the Repository

### ISSUE THREAD

**Issue by WeatherRouteing** [52North/WeatherRoutingTool#3]
I am writing to request access to the respective git repository mentioned earlier. Could you please provide me with the necessary permissions and instructions on how to clone “maripower”?

**Comment by MartinPontius** [comment]
Hi @WeatherRouteing, please see my answer in the [other issue](https://github.com/52North/WeatherRoutingTool/issues/2#issuecomment-2233024027).

**Comment by harshit4311** [comment]
Could you please assign this issue to me? I'd love working on this
